pipeline {
    stages {
		stage('Front-end') {
			agent {
				docker {
					image 'node:10'
					args '-v /root/.m2:/root/.m2 -p 8060:8060'
				}
			}
			stages {
				stage('Set Up') {
					steps {
						script {
							sh 'rm -rf front-end'
						}
					}
				}
				stage('SCM Checkout') {
					steps {
						script {
							sh 'git clone https://github.com/nmm131/jenkins.docker.spring.react.selenium_person-database.git front-end'
						}
					}
				}
				stage('Compile-Package-Test') {
					steps {
						script {
							dir('./front-end/client') {
								sh "npm install"
								sh "npm start &"
								sh "sleep 8m"
							}
						}
					}
				}
			}
		}
	}
}
